package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// ProfileChangedEvent : Triggered when switching to another profile or when renaming the current profile.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#profilechanged
type ProfileChangedEvent _event

// Type returns the event's update type.
func (e ProfileChangedEvent) Type() string { return e.UpdateType }

// StreamTC returns the event's stream timecode.
func (e ProfileChangedEvent) StreamTC() string { return e.StreamTimecode }

// RecTC returns the event's recording timecode.
func (e ProfileChangedEvent) RecTC() string { return e.RecTimecode }

// ProfileListChangedEvent : Triggered when a profile is created, added, renamed, or removed.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#profilelistchanged
type ProfileListChangedEvent _event

// Type returns the event's update type.
func (e ProfileListChangedEvent) Type() string { return e.UpdateType }

// StreamTC returns the event's stream timecode.
func (e ProfileListChangedEvent) StreamTC() string { return e.StreamTimecode }

// RecTC returns the event's recording timecode.
func (e ProfileListChangedEvent) RecTC() string { return e.RecTimecode }
