package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// RecordingStartingEvent :
//
// Note: `recordingFilename` is not provided in this event because this information
// is not available at the time this event is emitted.
//
// Since obs-websocket version: 0.3.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingstarting
type RecordingStartingEvent struct {
	_event `json:",squash"`
}

// RecordingStartedEvent : Recording started successfully.
//
// Since obs-websocket version: 0.3.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingstarted
type RecordingStartedEvent struct {
	// Absolute path to the file of the current recording.
	// Required: Yes.
	RecordingFilename string `json:"recordingFilename"`
	_event            `json:",squash"`
}

// RecordingStoppingEvent : A request to stop recording has been issued.
//
// Since obs-websocket version: 0.3.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingstopping
type RecordingStoppingEvent struct {
	// Absolute path to the file of the current recording.
	// Required: Yes.
	RecordingFilename string `json:"recordingFilename"`
	_event            `json:",squash"`
}

// RecordingStoppedEvent : Recording stopped successfully.
//
// Since obs-websocket version: 0.3.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingstopped
type RecordingStoppedEvent struct {
	// Absolute path to the file of the current recording.
	// Required: Yes.
	RecordingFilename string `json:"recordingFilename"`
	_event            `json:",squash"`
}

// RecordingPausedEvent : Current recording paused.
//
// Since obs-websocket version: 4.7.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingpaused
type RecordingPausedEvent struct {
	_event `json:",squash"`
}

// RecordingResumedEvent : Current recording resumed.
//
// Since obs-websocket version: 4.7.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingresumed
type RecordingResumedEvent struct {
	_event `json:",squash"`
}
