package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// SwitchTransitionEvent : The active transition has been changed.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#switchtransition
type SwitchTransitionEvent struct {
	// The name of the new active transition.
	// Required: Yes.
	TransitionName string `json:"transition-name"`
	_event
}

// Type returns the event's update type.
func (e SwitchTransitionEvent) Type() string { return e.UpdateType }

// StreamTC returns the event's stream timecode.
func (e SwitchTransitionEvent) StreamTC() string { return e.StreamTimecode }

// RecTC returns the event's recording timecode.
func (e SwitchTransitionEvent) RecTC() string { return e.RecTimecode }

// TransitionListChangedEvent : The list of available transitions has been modified.
// Transitions have been added, removed, or renamed.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#transitionlistchanged
type TransitionListChangedEvent _event

// Type returns the event's update type.
func (e TransitionListChangedEvent) Type() string { return e.UpdateType }

// StreamTC returns the event's stream timecode.
func (e TransitionListChangedEvent) StreamTC() string { return e.StreamTimecode }

// RecTC returns the event's recording timecode.
func (e TransitionListChangedEvent) RecTC() string { return e.RecTimecode }

// TransitionDurationChangedEvent : The active transition duration has been changed.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#transitiondurationchanged
type TransitionDurationChangedEvent struct {
	// New transition duration.
	// Required: Yes.
	NewDuration int `json:"new-duration"`
	_event
}

// Type returns the event's update type.
func (e TransitionDurationChangedEvent) Type() string { return e.UpdateType }

// StreamTC returns the event's stream timecode.
func (e TransitionDurationChangedEvent) StreamTC() string { return e.StreamTimecode }

// RecTC returns the event's recording timecode.
func (e TransitionDurationChangedEvent) RecTC() string { return e.RecTimecode }

// TransitionBeginEvent : A transition (other than "cut") has begun.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#transitionbegin
type TransitionBeginEvent struct {
	// Transition name.
	// Required: Yes.
	Name string `json:"name"`
	// Transition duration (in milliseconds).
	// Required: Yes.
	Duration int `json:"duration"`
	_event
}

// Type returns the event's update type.
func (e TransitionBeginEvent) Type() string { return e.UpdateType }

// StreamTC returns the event's stream timecode.
func (e TransitionBeginEvent) StreamTC() string { return e.StreamTimecode }

// RecTC returns the event's recording timecode.
func (e TransitionBeginEvent) RecTC() string { return e.RecTimecode }
