package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// PreviewSceneChangedEvent : The selected preview scene has changed (only available in Studio Mode).
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#previewscenechanged
type PreviewSceneChangedEvent struct {
	// Name of the scene being previewed.
	// Required: Yes.
	SceneName string `json:"scene-name"`
	// List of sources composing the scene.
	// Same specification as [`GetCurrentScene`](#getcurrentscene).
	// Required: Yes.
	Sources []map[string]interface{} `json:"sources"`
	_event  `json:",squash"`
}

// Type returns the event's update type.
func (e PreviewSceneChangedEvent) Type() string { return e.Type_ }

// StreamTimecode returns the event's stream timecode.
func (e PreviewSceneChangedEvent) StreamTimecode() string { return e.StreamTimecode_ }

// RecTimecode returns the event's recording timecode.
func (e PreviewSceneChangedEvent) RecTimecode() string { return e.RecTimecode_ }

// StudioModeSwitchedEvent : Studio Mode has been enabled or disabled.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#studiomodeswitched
type StudioModeSwitchedEvent struct {
	// The new enabled state of Studio Mode.
	// Required: Yes.
	NewState bool `json:"new-state"`
	_event   `json:",squash"`
}

// Type returns the event's update type.
func (e StudioModeSwitchedEvent) Type() string { return e.Type_ }

// StreamTimecode returns the event's stream timecode.
func (e StudioModeSwitchedEvent) StreamTimecode() string { return e.StreamTimecode_ }

// RecTimecode returns the event's recording timecode.
func (e StudioModeSwitchedEvent) RecTimecode() string { return e.RecTimecode_ }
