package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// GetTransitionListRequest : List of all transitions available in the frontend's dropdown menu. Since: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionlist
type GetTransitionListRequest _request

// ID returns the request's message ID.
func (r GetTransitionListRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetTransitionListRequest) Type() string { return r.RequestType }

// GetTransitionListResponse : Response for GetTransitionListRequest. Since: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionlist
type GetTransitionListResponse struct {
	CurrentTransition string      `json:"current-transition"` // Name of the currently active transition.
	Transitions       interface{} `json:"transitions"`        // List of transitions. TODO: Unknown type (Object|Array).
	TransitionsName   string      `json:"transitions[].name"` // Name of the transition.
	_response
}

// ID returns the response's message ID.
func (r GetTransitionListResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetTransitionListResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetTransitionListResponse) Err() string { return r.Error }

// GetCurrentTransitionRequest : Get the name of the currently selected transition in the frontend's dropdown menu. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getcurrenttransition
type GetCurrentTransitionRequest _request

// ID returns the request's message ID.
func (r GetCurrentTransitionRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetCurrentTransitionRequest) Type() string { return r.RequestType }

// GetCurrentTransitionResponse : Response for GetCurrentTransitionRequest. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getcurrenttransition
type GetCurrentTransitionResponse struct {
	Name     string `json:"name"`     // Name of the selected transition.
	Duration int    `json:"duration"` // Transition duration (in milliseconds) if supported by the transition. Optional.
	_response
}

// ID returns the response's message ID.
func (r GetCurrentTransitionResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetCurrentTransitionResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetCurrentTransitionResponse) Err() string { return r.Error }

// SetCurrentTransitionRequest : Set the active transition. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrenttransition
type SetCurrentTransitionRequest struct {
	TransitionName string `json:"transition-name"` // The name of the transition.
	_request
}

// ID returns the request's message ID.
func (r SetCurrentTransitionRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetCurrentTransitionRequest) Type() string { return r.RequestType }

// SetCurrentTransitionResponse : Response for SetCurrentTransitionRequest. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrenttransition
type SetCurrentTransitionResponse _response

// ID returns the response's message ID.
func (r SetCurrentTransitionResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetCurrentTransitionResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetCurrentTransitionResponse) Err() string { return r.Error }

// SetTransitionDurationRequest : Set the duration of the currently selected transition if supported. Since: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#settransitionduration
type SetTransitionDurationRequest struct {
	Duration int `json:"duration"` // Desired duration of the transition (in milliseconds).
	_request
}

// ID returns the request's message ID.
func (r SetTransitionDurationRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetTransitionDurationRequest) Type() string { return r.RequestType }

// SetTransitionDurationResponse : Response for SetTransitionDurationRequest. Since: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#settransitionduration
type SetTransitionDurationResponse _response

// ID returns the response's message ID.
func (r SetTransitionDurationResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetTransitionDurationResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetTransitionDurationResponse) Err() string { return r.Error }

// GetTransitionDurationRequest : Get the duration of the currently selected transition if supported. Since: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionduration
type GetTransitionDurationRequest _request

// ID returns the request's message ID.
func (r GetTransitionDurationRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetTransitionDurationRequest) Type() string { return r.RequestType }

// GetTransitionDurationResponse : Response for GetTransitionDurationRequest. Since: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionduration
type GetTransitionDurationResponse struct {
	TransitionDuration int `json:"transition-duration"` // Duration of the current transition (in milliseconds).
	_response
}

// ID returns the response's message ID.
func (r GetTransitionDurationResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetTransitionDurationResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetTransitionDurationResponse) Err() string { return r.Error }
