package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// GetTransitionListRequest : List of all transitions available in the frontend's dropdown menu.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionlist
type GetTransitionListRequest _request

// NewGetTransitionListRequest returns a new GetTransitionListRequest.
func NewGetTransitionListRequest() GetTransitionListRequest {
	return GetTransitionListRequest{MessageID: getMessageID(), RequestType: "GetTransitionList"}
}

// ID returns the request's message ID.
func (r GetTransitionListRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetTransitionListRequest) Type() string { return r.RequestType }

// GetTransitionListResponse : Response for GetTransitionListRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionlist
type GetTransitionListResponse struct {
	// Name of the currently active transition.
	// Required: Yes.
	CurrentTransition string `mapstructure:"current-transition"`
	// List of transitions.
	// Required: Yes.
	// TODO: Unknown type (Object|Array).
	Transitions interface{} `mapstructure:"transitions"`
	// Name of the transition.
	// Required: Yes.
	TransitionsName string `mapstructure:"transitions[].name"`
	_response       `mapstructure:",squash"`
}

// ID returns the response's message ID.
func (r GetTransitionListResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetTransitionListResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetTransitionListResponse) Err() string { return r.Error }

// GetCurrentTransitionRequest : Get the name of the currently selected transition in the frontend's dropdown menu.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getcurrenttransition
type GetCurrentTransitionRequest _request

// NewGetCurrentTransitionRequest returns a new GetCurrentTransitionRequest.
func NewGetCurrentTransitionRequest() GetCurrentTransitionRequest {
	return GetCurrentTransitionRequest{MessageID: getMessageID(), RequestType: "GetCurrentTransition"}
}

// ID returns the request's message ID.
func (r GetCurrentTransitionRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetCurrentTransitionRequest) Type() string { return r.RequestType }

// GetCurrentTransitionResponse : Response for GetCurrentTransitionRequest.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getcurrenttransition
type GetCurrentTransitionResponse struct {
	// Name of the selected transition.
	// Required: Yes.
	Name string `mapstructure:"name"`
	// Transition duration (in milliseconds) if supported by the transition.
	// Required: No.
	Duration  int `mapstructure:"duration"`
	_response `mapstructure:",squash"`
}

// ID returns the response's message ID.
func (r GetCurrentTransitionResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetCurrentTransitionResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetCurrentTransitionResponse) Err() string { return r.Error }

// SetCurrentTransitionRequest : Set the active transition.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrenttransition
type SetCurrentTransitionRequest struct {
	// The name of the transition.
	// Required: Yes.
	TransitionName string `json:"transition-name"`
	_request
}

// NewSetCurrentTransitionRequest returns a new SetCurrentTransitionRequest.
func NewSetCurrentTransitionRequest(transitionName string) SetCurrentTransitionRequest {
	return SetCurrentTransitionRequest{
		transitionName,
		_request{
			MessageID:   getMessageID(),
			RequestType: "SetCurrentTransition",
		},
	}

}

// ID returns the request's message ID.
func (r SetCurrentTransitionRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetCurrentTransitionRequest) Type() string { return r.RequestType }

// SetCurrentTransitionResponse : Response for SetCurrentTransitionRequest.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrenttransition
type SetCurrentTransitionResponse _response

// ID returns the response's message ID.
func (r SetCurrentTransitionResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetCurrentTransitionResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetCurrentTransitionResponse) Err() string { return r.Error }

// SetTransitionDurationRequest : Set the duration of the currently selected transition if supported.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#settransitionduration
type SetTransitionDurationRequest struct {
	// Desired duration of the transition (in milliseconds).
	// Required: Yes.
	Duration int `json:"duration"`
	_request
}

// NewSetTransitionDurationRequest returns a new SetTransitionDurationRequest.
func NewSetTransitionDurationRequest(duration int) SetTransitionDurationRequest {
	return SetTransitionDurationRequest{
		duration,
		_request{
			MessageID:   getMessageID(),
			RequestType: "SetTransitionDuration",
		},
	}

}

// ID returns the request's message ID.
func (r SetTransitionDurationRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetTransitionDurationRequest) Type() string { return r.RequestType }

// SetTransitionDurationResponse : Response for SetTransitionDurationRequest.
// Since obs-websocket version: 4.0.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#settransitionduration
type SetTransitionDurationResponse _response

// ID returns the response's message ID.
func (r SetTransitionDurationResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetTransitionDurationResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetTransitionDurationResponse) Err() string { return r.Error }

// GetTransitionDurationRequest : Get the duration of the currently selected transition if supported.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionduration
type GetTransitionDurationRequest _request

// NewGetTransitionDurationRequest returns a new GetTransitionDurationRequest.
func NewGetTransitionDurationRequest() GetTransitionDurationRequest {
	return GetTransitionDurationRequest{MessageID: getMessageID(), RequestType: "GetTransitionDuration"}
}

// ID returns the request's message ID.
func (r GetTransitionDurationRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetTransitionDurationRequest) Type() string { return r.RequestType }

// GetTransitionDurationResponse : Response for GetTransitionDurationRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#gettransitionduration
type GetTransitionDurationResponse struct {
	// Duration of the current transition (in milliseconds).
	// Required: Yes.
	TransitionDuration int `mapstructure:"transition-duration"`
	_response          `mapstructure:",squash"`
}

// ID returns the response's message ID.
func (r GetTransitionDurationResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetTransitionDurationResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetTransitionDurationResponse) Err() string { return r.Error }
