package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// StartStopReplayBufferRequest : Toggle the Replay Buffer on/off.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#startstopreplaybuffer
type StartStopReplayBufferRequest _request

// NewStartStopReplayBufferRequest returns a new StartStopReplayBufferRequest.
func NewStartStopReplayBufferRequest() StartStopReplayBufferRequest {
	return StartStopReplayBufferRequest{ID_: getMessageID(), Type_: "StartStopReplayBuffer"}
}

// ID returns the request's message ID.
func (r StartStopReplayBufferRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r StartStopReplayBufferRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r StartStopReplayBufferRequest) Send(c Client) (chan StartStopReplayBufferResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan StartStopReplayBufferResponse)
	go func() { future <- (<-generic).(StartStopReplayBufferResponse) }()
	return future, nil
}

// StartStopReplayBufferResponse : Response for StartStopReplayBufferRequest.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#startstopreplaybuffer
type StartStopReplayBufferResponse _response

// ID returns the response's message ID.
func (r StartStopReplayBufferResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r StartStopReplayBufferResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r StartStopReplayBufferResponse) Error() string { return r.Error_ }

// StartReplayBufferRequest : Start recording into the Replay Buffer.
// Will return an `error` if the Replay Buffer is already active or if the
// "Save Replay Buffer" hotkey is not set in OBS' settings.
// Setting this hotkey is mandatory, even when triggering saves only
// through obs-websocket.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#startreplaybuffer
type StartReplayBufferRequest _request

// NewStartReplayBufferRequest returns a new StartReplayBufferRequest.
func NewStartReplayBufferRequest() StartReplayBufferRequest {
	return StartReplayBufferRequest{ID_: getMessageID(), Type_: "StartReplayBuffer"}
}

// ID returns the request's message ID.
func (r StartReplayBufferRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r StartReplayBufferRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r StartReplayBufferRequest) Send(c Client) (chan StartReplayBufferResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan StartReplayBufferResponse)
	go func() { future <- (<-generic).(StartReplayBufferResponse) }()
	return future, nil
}

// StartReplayBufferResponse : Response for StartReplayBufferRequest.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#startreplaybuffer
type StartReplayBufferResponse _response

// ID returns the response's message ID.
func (r StartReplayBufferResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r StartReplayBufferResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r StartReplayBufferResponse) Error() string { return r.Error_ }

// StopReplayBufferRequest : Stop recording into the Replay Buffer.
// Will return an `error` if the Replay Buffer is not active.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#stopreplaybuffer
type StopReplayBufferRequest _request

// NewStopReplayBufferRequest returns a new StopReplayBufferRequest.
func NewStopReplayBufferRequest() StopReplayBufferRequest {
	return StopReplayBufferRequest{ID_: getMessageID(), Type_: "StopReplayBuffer"}
}

// ID returns the request's message ID.
func (r StopReplayBufferRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r StopReplayBufferRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r StopReplayBufferRequest) Send(c Client) (chan StopReplayBufferResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan StopReplayBufferResponse)
	go func() { future <- (<-generic).(StopReplayBufferResponse) }()
	return future, nil
}

// StopReplayBufferResponse : Response for StopReplayBufferRequest.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#stopreplaybuffer
type StopReplayBufferResponse _response

// ID returns the response's message ID.
func (r StopReplayBufferResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r StopReplayBufferResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r StopReplayBufferResponse) Error() string { return r.Error_ }

// SaveReplayBufferRequest : Flush and save the contents of the Replay Buffer to disk
// This is
// basically the same as triggering the "Save Replay Buffer" hotkey.
// Will return an `error` if the Replay Buffer is not active.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#savereplaybuffer
type SaveReplayBufferRequest _request

// NewSaveReplayBufferRequest returns a new SaveReplayBufferRequest.
func NewSaveReplayBufferRequest() SaveReplayBufferRequest {
	return SaveReplayBufferRequest{ID_: getMessageID(), Type_: "SaveReplayBuffer"}
}

// ID returns the request's message ID.
func (r SaveReplayBufferRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r SaveReplayBufferRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r SaveReplayBufferRequest) Send(c Client) (chan SaveReplayBufferResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan SaveReplayBufferResponse)
	go func() { future <- (<-generic).(SaveReplayBufferResponse) }()
	return future, nil
}

// SaveReplayBufferResponse : Response for SaveReplayBufferRequest.
// Since obs-websocket version: 4.2.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#savereplaybuffer
type SaveReplayBufferResponse _response

// ID returns the response's message ID.
func (r SaveReplayBufferResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r SaveReplayBufferResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r SaveReplayBufferResponse) Error() string { return r.Error_ }
