package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// SetCurrentSceneRequest : Switch to the specified scene.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrentscene
type SetCurrentSceneRequest struct {
	// Name of the scene to switch to.
	// Required: Yes.
	SceneName string `json:"scene-name"`
	_request
}

// NewSetCurrentSceneRequest returns a new SetCurrentSceneRequest.
func NewSetCurrentSceneRequest(sceneName string) SetCurrentSceneRequest {
	return SetCurrentSceneRequest{
		sceneName,
		_request{
			MessageID:   getMessageID(),
			RequestType: "SetCurrentScene",
		},
	}

}

// ID returns the request's message ID.
func (r SetCurrentSceneRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetCurrentSceneRequest) Type() string { return r.RequestType }

// SetCurrentSceneResponse : Response for SetCurrentSceneRequest.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrentscene
type SetCurrentSceneResponse _response

// ID returns the response's message ID.
func (r SetCurrentSceneResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetCurrentSceneResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetCurrentSceneResponse) Err() string { return r.Error }

// GetCurrentSceneRequest : Get the current scene's name and source items.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getcurrentscene
type GetCurrentSceneRequest _request

// NewGetCurrentSceneRequest returns a new GetCurrentSceneRequest.
func NewGetCurrentSceneRequest() GetCurrentSceneRequest {
	return GetCurrentSceneRequest{MessageID: getMessageID(), RequestType: "GetCurrentScene"}
}

// ID returns the request's message ID.
func (r GetCurrentSceneRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetCurrentSceneRequest) Type() string { return r.RequestType }

// GetCurrentSceneResponse : Response for GetCurrentSceneRequest.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getcurrentscene
type GetCurrentSceneResponse struct {
	// Name of the currently active scene.
	// Required: Yes.
	Name string `mapstructure:"name"`
	// Ordered list of the current scene's source items.
	// Required: Yes.
	// TODO: Unknown type (Source|Array).
	Sources   interface{} `mapstructure:"sources"`
	_response `mapstructure:",squash"`
}

// ID returns the response's message ID.
func (r GetCurrentSceneResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetCurrentSceneResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetCurrentSceneResponse) Err() string { return r.Error }

// GetSceneListRequest : Get a list of scenes in the currently active profile.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getscenelist
type GetSceneListRequest _request

// NewGetSceneListRequest returns a new GetSceneListRequest.
func NewGetSceneListRequest() GetSceneListRequest {
	return GetSceneListRequest{MessageID: getMessageID(), RequestType: "GetSceneList"}
}

// ID returns the request's message ID.
func (r GetSceneListRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetSceneListRequest) Type() string { return r.RequestType }

// GetSceneListResponse : Response for GetSceneListRequest.
// Since obs-websocket version: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getscenelist
type GetSceneListResponse struct {
	// Name of the currently active scene.
	// Required: Yes.
	CurrentScene string `mapstructure:"current-scene"`
	// Ordered list of the current profile's scenes (See `[GetCurrentScene](#getcurrentscene)` for more information).
	// Required: Yes.
	// TODO: Unknown type (Scene|Array).
	Scenes    interface{} `mapstructure:"scenes"`
	_response `mapstructure:",squash"`
}

// ID returns the response's message ID.
func (r GetSceneListResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetSceneListResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetSceneListResponse) Err() string { return r.Error }

// SetSceneItemOrderRequest : Changes the order of scene items in the requested scene.
// Since obs-websocket version: Unreleased.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setsceneitemorder
type SetSceneItemOrderRequest struct {
	// Name of the scene to reorder (defaults to current).
	// Required: No.
	Scene string `json:"scene"`
	// Ordered list of objects with name and/or id specified.
	// Id prefered due to uniqueness per scene.
	// Required: Yes.
	// TODO: Unknown type (Scene|Array).
	Items interface{} `json:"items"`
	// Id of a specific scene item.
	// Unique on a scene by scene basis.
	// Required: No.
	ItemsID int `json:"items[].id"`
	// Name of a scene item.
	// Sufficiently unique if no scene items share sources within the scene.
	// Required: No.
	ItemsName string `json:"items[].name"`
	_request
}

// NewSetSceneItemOrderRequest returns a new SetSceneItemOrderRequest.
func NewSetSceneItemOrderRequest(
	scene string,
	items interface{},
	itemsID int,
	itemsName string,
) SetSceneItemOrderRequest {
	return SetSceneItemOrderRequest{
		scene,
		items,
		itemsID,
		itemsName,
		_request{
			MessageID:   getMessageID(),
			RequestType: "SetSceneItemOrder",
		},
	}

}

// ID returns the request's message ID.
func (r SetSceneItemOrderRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetSceneItemOrderRequest) Type() string { return r.RequestType }

// SetSceneItemOrderResponse : Response for SetSceneItemOrderRequest.
// Since obs-websocket version: Unreleased.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setsceneitemorder
type SetSceneItemOrderResponse _response

// ID returns the response's message ID.
func (r SetSceneItemOrderResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetSceneItemOrderResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetSceneItemOrderResponse) Err() string { return r.Error }
