package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// GetVersionRequest : Returns the latest version of the plugin and the API. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getversion
type GetVersionRequest _request

// ID returns the request's message ID.
func (r GetVersionRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetVersionRequest) Type() string { return r.RequestType }

// GetVersionResponse : Response for GetVersionRequest. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getversion
type GetVersionResponse struct {
	Version             float64 `json:"version"`               // OBSRemote compatible API version. Fixed to 1.1 for retrocompatibility.
	ObsWebsocketVersion string  `json:"obs-websocket-version"` // obs-websocket plugin version.
	ObsStudioVersion    string  `json:"obs-studio-version"`    // OBS Studio program version.
	AvailableRequests   string  `json:"available-requests"`    // List of available request types, formatted as a comma-separated list string (e.g. : "Method1,Method2,Method3").
	_response
}

// ID returns the response's message ID.
func (r GetVersionResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetVersionResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetVersionResponse) Err() string { return r.Error }

// GetAuthRequiredRequest : Tells the client if authentication is required. If so, returns authentication parameters `challenge` and `salt` (see "Authentication" for more information). Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getauthrequired
type GetAuthRequiredRequest _request

// ID returns the request's message ID.
func (r GetAuthRequiredRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetAuthRequiredRequest) Type() string { return r.RequestType }

// GetAuthRequiredResponse : Response for GetAuthRequiredRequest. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getauthrequired
type GetAuthRequiredResponse struct {
	AuthRequired bool   `json:"authRequired"` // Indicates whether authentication is required.
	Challenge    string `json:"challenge"`    // Optional.
	Salt         string `json:"salt"`         // Optional.
	_response
}

// ID returns the response's message ID.
func (r GetAuthRequiredResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetAuthRequiredResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetAuthRequiredResponse) Err() string { return r.Error }

// AuthenticateRequest : Attempt to authenticate the client to the server. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#authenticate
type AuthenticateRequest struct {
	Auth string `json:"auth"` // Response to the auth challenge (see "Authentication" for more information).
	_request
}

// ID returns the request's message ID.
func (r AuthenticateRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r AuthenticateRequest) Type() string { return r.RequestType }

// AuthenticateResponse : Response for AuthenticateRequest. Since: 0.3.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#authenticate
type AuthenticateResponse _response

// ID returns the response's message ID.
func (r AuthenticateResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r AuthenticateResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r AuthenticateResponse) Err() string { return r.Error }

// SetHeartbeatRequest : Enable/disable sending of the Heartbeat event. Since: 4.3.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setheartbeat
type SetHeartbeatRequest struct {
	Enable bool `json:"enable"` // Starts/Stops emitting heartbeat messages.
	_request
}

// ID returns the request's message ID.
func (r SetHeartbeatRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetHeartbeatRequest) Type() string { return r.RequestType }

// SetHeartbeatResponse : Response for SetHeartbeatRequest. Since: 4.3.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setheartbeat
type SetHeartbeatResponse _response

// ID returns the response's message ID.
func (r SetHeartbeatResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetHeartbeatResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetHeartbeatResponse) Err() string { return r.Error }

// SetFilenameFormattingRequest : Set the filename formatting string. Since: 4.3.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setfilenameformatting
type SetFilenameFormattingRequest struct {
	FilenameFormatting string `json:"filename-formatting"` // Filename formatting string to set.
	_request
}

// ID returns the request's message ID.
func (r SetFilenameFormattingRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r SetFilenameFormattingRequest) Type() string { return r.RequestType }

// SetFilenameFormattingResponse : Response for SetFilenameFormattingRequest. Since: 4.3.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setfilenameformatting
type SetFilenameFormattingResponse _response

// ID returns the response's message ID.
func (r SetFilenameFormattingResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r SetFilenameFormattingResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r SetFilenameFormattingResponse) Err() string { return r.Error }

// GetFilenameFormattingRequest : Get the filename formatting string. Since: 4.3.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getfilenameformatting
type GetFilenameFormattingRequest _request

// ID returns the request's message ID.
func (r GetFilenameFormattingRequest) ID() string { return r.MessageID }

// Type returns the request's message type.
func (r GetFilenameFormattingRequest) Type() string { return r.RequestType }

// GetFilenameFormattingResponse : Response for GetFilenameFormattingRequest. Since: 4.3.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getfilenameformatting
type GetFilenameFormattingResponse struct {
	FilenameFormatting string `json:"filename-formatting"` // Current filename formatting string.
	_response
}

// ID returns the response's message ID.
func (r GetFilenameFormattingResponse) ID() string { return r.MessageID }

// Stat returns the response's status.
func (r GetFilenameFormattingResponse) Stat() string { return r.Status }

// Err returns the response's error.
func (r GetFilenameFormattingResponse) Err() string { return r.Error }
