package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

// GetStudioModeStatusRequest : Indicates if Studio Mode is currently enabled.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getstudiomodestatus
type GetStudioModeStatusRequest _request

// NewGetStudioModeStatusRequest returns a new GetStudioModeStatusRequest.
func NewGetStudioModeStatusRequest() GetStudioModeStatusRequest {
	return GetStudioModeStatusRequest{ID_: getMessageID(), Type_: "GetStudioModeStatus"}
}

// ID returns the request's message ID.
func (r GetStudioModeStatusRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r GetStudioModeStatusRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r GetStudioModeStatusRequest) Send(c Client) (chan GetStudioModeStatusResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan GetStudioModeStatusResponse)
	go func() { future <- (<-generic).(GetStudioModeStatusResponse) }()
	return future, nil
}

// GetStudioModeStatusResponse : Response for GetStudioModeStatusRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getstudiomodestatus
type GetStudioModeStatusResponse struct {
	// Indicates if Studio Mode is enabled.
	// Required: Yes.
	StudioMode bool `json:"studio-mode"`
	_response  `json:",squash"`
}

// ID returns the response's message ID.
func (r GetStudioModeStatusResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r GetStudioModeStatusResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r GetStudioModeStatusResponse) Error() string { return r.Error_ }

// GetPreviewSceneRequest : Get the name of the currently previewed scene and its list of sources.
// Will return an `error` if Studio Mode is not enabled.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getpreviewscene
type GetPreviewSceneRequest _request

// NewGetPreviewSceneRequest returns a new GetPreviewSceneRequest.
func NewGetPreviewSceneRequest() GetPreviewSceneRequest {
	return GetPreviewSceneRequest{ID_: getMessageID(), Type_: "GetPreviewScene"}
}

// ID returns the request's message ID.
func (r GetPreviewSceneRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r GetPreviewSceneRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r GetPreviewSceneRequest) Send(c Client) (chan GetPreviewSceneResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan GetPreviewSceneResponse)
	go func() { future <- (<-generic).(GetPreviewSceneResponse) }()
	return future, nil
}

// GetPreviewSceneResponse : Response for GetPreviewSceneRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#getpreviewscene
type GetPreviewSceneResponse struct {
	// The name of the active preview scene.
	// Required: Yes.
	Name string `json:"name"`
	// Required: Yes.
	Sources   []map[string]interface{} `json:"sources"`
	_response `json:",squash"`
}

// ID returns the response's message ID.
func (r GetPreviewSceneResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r GetPreviewSceneResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r GetPreviewSceneResponse) Error() string { return r.Error_ }

// SetPreviewSceneRequest : Set the active preview scene.
// Will return an `error` if Studio Mode is not enabled.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setpreviewscene
type SetPreviewSceneRequest struct {
	// The name of the scene to preview.
	// Required: Yes.
	SceneName string `json:"scene-name"`
	_request  `json:",squash"`
}

// NewSetPreviewSceneRequest returns a new SetPreviewSceneRequest.
func NewSetPreviewSceneRequest(sceneName string) SetPreviewSceneRequest {
	return SetPreviewSceneRequest{
		sceneName,
		_request{
			ID_:   getMessageID(),
			Type_: "SetPreviewScene",
		},
	}

}

// ID returns the request's message ID.
func (r SetPreviewSceneRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r SetPreviewSceneRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r SetPreviewSceneRequest) Send(c Client) (chan SetPreviewSceneResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan SetPreviewSceneResponse)
	go func() { future <- (<-generic).(SetPreviewSceneResponse) }()
	return future, nil
}

// SetPreviewSceneResponse : Response for SetPreviewSceneRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setpreviewscene
type SetPreviewSceneResponse _response

// ID returns the response's message ID.
func (r SetPreviewSceneResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r SetPreviewSceneResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r SetPreviewSceneResponse) Error() string { return r.Error_ }

// TransitionToProgramRequest : Transitions the currently previewed scene to the main output.
// Will return an `error` if Studio Mode is not enabled.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#transitiontoprogram
type TransitionToProgramRequest struct {
	// Change the active transition before switching scenes.
	// Defaults to the active transition.
	// Required: No.
	WithTransition map[string]interface{} `json:"with-transition"`
	// Name of the transition.
	// Required: Yes.
	WithTransitionName string `json:"with-transition.name"`
	// Transition duration (in milliseconds).
	// Required: No.
	WithTransitionDuration int `json:"with-transition.duration"`
	_request               `json:",squash"`
}

// NewTransitionToProgramRequest returns a new TransitionToProgramRequest.
func NewTransitionToProgramRequest(
	withTransition map[string]interface{},
	withTransitionName string,
	withTransitionDuration int,
) TransitionToProgramRequest {
	return TransitionToProgramRequest{
		withTransition,
		withTransitionName,
		withTransitionDuration,
		_request{
			ID_:   getMessageID(),
			Type_: "TransitionToProgram",
		},
	}

}

// ID returns the request's message ID.
func (r TransitionToProgramRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r TransitionToProgramRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r TransitionToProgramRequest) Send(c Client) (chan TransitionToProgramResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan TransitionToProgramResponse)
	go func() { future <- (<-generic).(TransitionToProgramResponse) }()
	return future, nil
}

// TransitionToProgramResponse : Response for TransitionToProgramRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#transitiontoprogram
type TransitionToProgramResponse _response

// ID returns the response's message ID.
func (r TransitionToProgramResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r TransitionToProgramResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r TransitionToProgramResponse) Error() string { return r.Error_ }

// EnableStudioModeRequest : Enables Studio Mode.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#enablestudiomode
type EnableStudioModeRequest _request

// NewEnableStudioModeRequest returns a new EnableStudioModeRequest.
func NewEnableStudioModeRequest() EnableStudioModeRequest {
	return EnableStudioModeRequest{ID_: getMessageID(), Type_: "EnableStudioMode"}
}

// ID returns the request's message ID.
func (r EnableStudioModeRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r EnableStudioModeRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r EnableStudioModeRequest) Send(c Client) (chan EnableStudioModeResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan EnableStudioModeResponse)
	go func() { future <- (<-generic).(EnableStudioModeResponse) }()
	return future, nil
}

// EnableStudioModeResponse : Response for EnableStudioModeRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#enablestudiomode
type EnableStudioModeResponse _response

// ID returns the response's message ID.
func (r EnableStudioModeResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r EnableStudioModeResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r EnableStudioModeResponse) Error() string { return r.Error_ }

// DisableStudioModeRequest : Disables Studio Mode.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#disablestudiomode
type DisableStudioModeRequest _request

// NewDisableStudioModeRequest returns a new DisableStudioModeRequest.
func NewDisableStudioModeRequest() DisableStudioModeRequest {
	return DisableStudioModeRequest{ID_: getMessageID(), Type_: "DisableStudioMode"}
}

// ID returns the request's message ID.
func (r DisableStudioModeRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r DisableStudioModeRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r DisableStudioModeRequest) Send(c Client) (chan DisableStudioModeResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan DisableStudioModeResponse)
	go func() { future <- (<-generic).(DisableStudioModeResponse) }()
	return future, nil
}

// DisableStudioModeResponse : Response for DisableStudioModeRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#disablestudiomode
type DisableStudioModeResponse _response

// ID returns the response's message ID.
func (r DisableStudioModeResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r DisableStudioModeResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r DisableStudioModeResponse) Error() string { return r.Error_ }

// ToggleStudioModeRequest : Toggles Studio Mode.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#togglestudiomode
type ToggleStudioModeRequest _request

// NewToggleStudioModeRequest returns a new ToggleStudioModeRequest.
func NewToggleStudioModeRequest() ToggleStudioModeRequest {
	return ToggleStudioModeRequest{ID_: getMessageID(), Type_: "ToggleStudioMode"}
}

// ID returns the request's message ID.
func (r ToggleStudioModeRequest) ID() string { return r.ID_ }

// Type returns the request's message type.
func (r ToggleStudioModeRequest) Type() string { return r.Type_ }

// Send sends the request and returns a channel to which the response will be sent.
func (r ToggleStudioModeRequest) Send(c Client) (chan ToggleStudioModeResponse, error) {
	generic, err := c.SendRequest(r)
	if err != nil {
		return nil, err
	}
	future := make(chan ToggleStudioModeResponse)
	go func() { future <- (<-generic).(ToggleStudioModeResponse) }()
	return future, nil
}

// ToggleStudioModeResponse : Response for ToggleStudioModeRequest.
// Since obs-websocket version: 4.1.0.
// https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#togglestudiomode
type ToggleStudioModeResponse _response

// ID returns the response's message ID.
func (r ToggleStudioModeResponse) ID() string { return r.ID_ }

// Status returns the response's status.
func (r ToggleStudioModeResponse) Status() string { return r.Status_ }

// Error returns the response's error.
func (r ToggleStudioModeResponse) Error() string { return r.Error_ }
