package obsws

// This file is automatically generated.
// https://github.com/christopher-dG/go-obs-websocket/blob/master/codegen/protocol.py

var eventMap = map[string]Event{
	"SwitchScenes":               &SwitchScenesEvent{},
	"ScenesChanged":              &ScenesChangedEvent{},
	"SceneCollectionChanged":     &SceneCollectionChangedEvent{},
	"SceneCollectionListChanged": &SceneCollectionListChangedEvent{},
	"SwitchTransition":           &SwitchTransitionEvent{},
	"TransitionListChanged":      &TransitionListChangedEvent{},
	"TransitionDurationChanged":  &TransitionDurationChangedEvent{},
	"TransitionBegin":            &TransitionBeginEvent{},
	"ProfileChanged":             &ProfileChangedEvent{},
	"ProfileListChanged":         &ProfileListChangedEvent{},
	"StreamStarting":             &StreamStartingEvent{},
	"StreamStarted":              &StreamStartedEvent{},
	"StreamStopping":             &StreamStoppingEvent{},
	"StreamStopped":              &StreamStoppedEvent{},
	"StreamStatus":               &StreamStatusEvent{},
	"RecordingStarting":          &RecordingStartingEvent{},
	"RecordingStarted":           &RecordingStartedEvent{},
	"RecordingStopping":          &RecordingStoppingEvent{},
	"RecordingStopped":           &RecordingStoppedEvent{},
	"ReplayStarting":             &ReplayStartingEvent{},
	"ReplayStarted":              &ReplayStartedEvent{},
	"ReplayStopping":             &ReplayStoppingEvent{},
	"ReplayStopped":              &ReplayStoppedEvent{},
	"Exiting":                    &ExitingEvent{},
	"Heartbeat":                  &HeartbeatEvent{},
	"SourceOrderChanged":         &SourceOrderChangedEvent{},
	"SceneItemAdded":             &SceneItemAddedEvent{},
	"SceneItemRemoved":           &SceneItemRemovedEvent{},
	"SceneItemVisibilityChanged": &SceneItemVisibilityChangedEvent{},
	"PreviewSceneChanged":        &PreviewSceneChangedEvent{},
	"StudioModeSwitched":         &StudioModeSwitchedEvent{},
}
